/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EqualisGovernor } from "./EqualisGovernor";
export type { TimelockSetup } from "./TimelockSetup";
