/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EqualisGovernor__factory } from "./EqualisGovernor__factory";
export { TimelockSetup__factory } from "./TimelockSetup__factory";
